class ItemsConstants {
  static const List<String> genderItems = ['FEMALE', 'OTHER', "MALE"];

  static const List<String> maritalItems = [
    "SINGLE",
    "MARRIED",
    "DIVORCED",
  ];
  static const List<String> cityItems = [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Ahmedabad',
    'Chennai',
    'Kolkata',
    'Surat',
    'Pune',
    'Jaipur',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Indore',
    'Thane',
    'Bhopal',
    'Visakhapatnam',
    'Pimpri',
    'Patna',
    'Vadodara',
    'Ghaziabad',
    'Ludhiana',
    'Agra',
    'Nashik',
    'Faridabad',
    'Meerut',
    'Rajkot',
    'Kalyan',
    'Vasai',
    'Varanasi',
    'Srinagar',
    'Aurangabad',
    'Dhanbad',
    'Amritsar',
    'Navi',
    'Allahabad',
    'Ranchi',
    'Haora',
    'Coimbatore',
    'Jabalpur',
    'Gwalior',
    'Vijayawada',
    'Jodhpur',
    'Madurai',
    'Raipur',
  ];
  static const List<String> stateItems = [
    'Andhra',
    'Arunachal',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal',
    'Dharamshala',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya',
    'Maharashtra',
    'Nagpur',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil',
    'Telangana',
    'Tripura',
    'Uttar',
    'Uttarakhand',
  ];
  static const List<String> countryItems = [
    'India',
  ];
  static const List<String> vaccineItems1 = ["Covid Dose 1", "Covid Dose 2", "Covid Dose 3"];
  static const List<String> vaccineItems2 = ["Yellow Fever Card", "Green Fever Card", "Red Fever Card"];
  static const List<String> vaccineItems3 = ["Vaccine 1", "Vaccine 2", "Vaccine 3"];
  static const List<String> reportType1 = ["Blood Test", "Urine Test", "Eye Test"];
  static const List<String> reportType2 = ["Body Test", "Nose Test", "Mouth Test"];
}
